name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      VOLT_API_P12_FILE: ${{ secrets.VOLT_API_P12_FILE }}
      VES_P12_PASSWORD: ${{ secrets.VES_P12_PASSWORD }}
    # environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


      # - name: Setup Terraform variables
      #   id: vars
      #   run: |-
      #     cat > pipeline.auto.tfvars <<EOF
      #     API_P12_PATH = "../../creds/galileo.console.ves.volterra.io.api-creds.p12"
      #     TENANT       = "galileo"
      #     NAMESPACE    = "arch"
      #     SHORTNAME    = "nginx-cc1"
      #     ORIGIN_PORT  = 80
      #     ORIGIN_IP    = "10.0.0.3"
      #     ORIGIN_SITE  = "gcp-test-site"
      #     DOMAIN_NAME  = "testing.vol"
      #     EOF
      - name: Env Var Debug
        id: fmt
        run: echo "$VES_P12_PASSWORD"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      # - name: 'Terraform Init'
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 1.2.4
      #     tf_actions_subcommand: 'init'
      #     tf_actions_working_dir: '.'
      #     tf_actions_comment: true
      #     tf_actions_cli_credentials_token: ${{ secrets.TF_API_TOKEN }}
      #     args: '-var-file="vars.tfvars"'

      - name: Terraform Validate
        id: validate
        run: terraform validate

      # - name: 'Terraform Validate'
      #   id: validate
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 1.2.4
      #     tf_actions_subcommand: 'validate'
      #     tf_actions_working_dir: '.'
      #     tf_actions_comment: true
      #     tf_actions_cli_credentials_token: ${{ secrets.TF_API_TOKEN }}
      #     args: '-var-file="vars.tfvars"'

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false 
        continue-on-error: true

      # - name: 'Terraform Plan'
      #   id: plan
      #   if: github.event_name == 'pull_request'
      #   uses: hashicorp/terraform-github-actions@master
      #   continue-on-error: true
      #   with:
      #     tf_actions_version: 1.2.4
      #     tf_actions_subcommand: 'plan'
      #     tf_actions_working_dir: '.'
      #     tf_actions_comment: true
      #     tf_actions_cli_credentials_token: ${{ secrets.TF_API_TOKEN }}
      #     args: '-input=false -var-file="vars.tfvars"'

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false 

      # - name: 'Terraform Apply'
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 1.2.4
      #     tf_actions_subcommand: 'apply'
      #     tf_actions_working_dir: '.'
      #     tf_actions_comment: true
      #     tf_actions_cli_credentials_token: ${{ secrets.TF_API_TOKEN }}
      #     args: ' -auto-approve -input=false -var-file="vars.tfvars"'